# Generated by Django 6.0.4 on 2026-05-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_package_images_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20),
        ),
    ]
