# Generated by Django 6.0.4 on 2026-05-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cartitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(db_column='PackageId', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='users.package')),
            ],
            options={
                'db_table': 'Discounts',
            },
        ),
    ]
