# Generated by Django 6.0.4 on 2026-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_reservation_minutes_cartitems_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='reservation_minutes',
            field=models.PositiveIntegerField(db_column='ReservationMinutes', default=15, help_text='Minutes a user may hold this package in the cart without completing purchase.'),
        ),
    ]
