# Generated by Django 6.0.4 on 2026-05-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_package_reservation_minutes'),
        ('users', '0015_replace_packages_with_tours'),
    ]

    operations = [
    ]
