# Generated by Django 6.0.4 on 2026-05-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cancellation_hours',
            field=models.PositiveIntegerField(db_column='CancellationHours', default=24, help_text='How many hours before the tour the user can cancel.'),
        ),
        migrations.AddField(
            model_name='package',
            name='tour_datetime',
            field=models.DateTimeField(blank=True, db_column='TourDateTime', help_text='Date and time of the tour.', null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], db_column='Status', default='Reserved', max_length=20),
        ),
    ]
