# Generated by Django 6.0.4 on 2026-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_package_cancellation_hours_package_tour_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='tour_access_code',
            field=models.CharField(blank=True, db_column='TourAccessCode', max_length=8, null=True),
        ),
    ]
