# Generated by Django 6.0.4 on 2026-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_cartitem_tour_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PepperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=120)),
                ('description', models.TextField(db_column='Description')),
                ('spiciness_level', models.PositiveSmallIntegerField(db_column='SpicinessLevel', default=1)),
                ('origin', models.CharField(blank=True, db_column='Origin', max_length=120)),
                ('usage', models.TextField(blank=True, db_column='Usage')),
                ('fun_fact', models.TextField(blank=True, db_column='FunFact')),
                ('image', models.ImageField(blank=True, db_column='Image', null=True, upload_to='peppers/')),
                ('qr_code_value', models.CharField(blank=True, db_column='QRCodeValue', max_length=50, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'PepperTypes',
            },
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tour_access_code',
            field=models.CharField(blank=True, db_column='TourAccessCode', max_length=6, null=True),
        ),
    ]
