# Generated by Django 6.0.4 on 2026-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_peppertype_alter_cartitem_tour_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='peppertype',
            name='qr_code_image',
            field=models.ImageField(blank=True, db_column='QRCodeImage', null=True, upload_to='pepper_qr/'),
        ),
    ]
