# Generated by Django 6.0.4 on 2026-06-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
              ('users', '0020_peppertype_alter_cartitem_tour_access_code'),
]
    

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='content')),
                ('rating', models.PositiveSmallIntegerField(db_column='rating', default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user')),
            ],
            options={
                'db_table': 'FEEDBACKS',
            },
        ),
    ]
