# Generated by Django 6.0.4 on 2026-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_peppertype_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='peppertype',
            name='guide_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
