# Generated by Django 6.0.4 on 2026-06-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_feedback'),
        ('users', '0022_peppertype_guide_text'),
    ]

    operations = [
    ]
