# Generated by Django 6.0.4 on 2026-06-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, db_column='Image', null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_url',
            field=models.CharField(db_column='image_url', default='', max_length=500),
        ),
    ]
