name: Deploy Django to Azure

on:
  push:
    branches:
      - develop
      - Package-management
      - main

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: Hadinarim
  PYTHON_VERSION: "3.12"

jobs:
  build-test-deploy:
    runs-on: windows-2022

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test users

      - name: Zip app
        run: |
          powershell Compress-Archive -Path * -DestinationPath app.zip

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip

      - name: Run database migrations
        run: |
          python manage.py migrate